Finish with the Desktop version
Ibnballo1/Portfolio-setup-and-mobile-version-skeleton pull request #6
Opened 2022-02-18 22:39 UTC by Ibnballo1

I added the work sections, about section, and the contact form of the desktop version to my portfolio.

2022-02-19 01:53 UTC, Donard97 requested changes
## Hi @Ibnballo1 , 👋  

_You did excellent work until now!  👏 💯 💯_ 

You have a few more things to fix but you are already there. You can do it! 💪 

![hgiphy](https://user-images.githubusercontent.com/74506933/154781434-6d53323e-228a-4d3b-87ae-852b2284b665.gif)


## HIGHLIGHTS ✅ 

> There are no linter errors ✔️ 
> PR title and description are descriptive ✔️ 
> There are a lot of commits and they are meaningful ✔️ 
> The README file is professional ✔️



## Required Changes ♻️

- [ ] Please check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] I suggest you to put a screenshot of your project on README file to be more professional

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-19 01:53 UTC, Donard97 commented on index.html
>                              <p class="texts text-3">2015</p>
- [ ] I suggest you change h1 to h2 or lower because following Semantic HTML is not allowed to have more than two tag h1 and it should be at the beginning of the page. Keep rocking 💪

2022-02-19 01:53 UTC, Donard97 commented on index.html
>                              <p class="count"></p>
- [ ] I suggest you change h1 to h2 or lower because following Semantic HTML is not allowed to have more than two tag h1 and it should be at the beginning of the page. Keep rocking 💪

2022-02-19 01:53 UTC, Donard97 commented on index.html
> +                        <h1>Facebook 360</h1>
- [ ] I suggest you change h1 to h2 or lower because following Semantic HTML is not allowed to have more than two tag h1 and it should be at the beginning of the page. Keep rocking 💪

2022-02-19 01:53 UTC, Donard97 commented on index.html
> +                        <h1>Uber Navigation</h1>
- [ ] I suggest you change h1 to h2 or lower because following Semantic HTML is not allowed to have more than two tag h1 and it should be at the beginning of the page. Keep rocking 💪

2022-02-19 01:53 UTC, Donard97 commented on styles.css
> +    height: 2694px;
- [ ]  Good job on the work you have done but please fix the design of the work section for the screens from 992px to 1432px because it is breaking.

Here you have a screenshot of the first section:

![image](https://user-images.githubusercontent.com/74506933/154780846-0828d204-bb6c-4a7f-980b-bfd863f8ec29.png)

2022-02-19 05:45 UTC, prolajumokeoni requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good PR ✔️ 
- Good commit messages ✔️ 
- No linter errors ✔️ 


## Required Changes ♻️
_Check the comments under the review._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 05:45 UTC, prolajumokeoni commented on styles.css
> +    height: 2694px;
- [ ] Kindly screen size for your desktop version as requested by the previous reviewer, try to make your design look like the original design
- [ ] Kindly go through the [project requirements ](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md) You should assume that the desktop width should be in 992px - 1100px range
- Making all these changes will make your project look like the original design 💪🏿

2022-02-19 05:45 UTC, prolajumokeoni commented on styles.css
> +    padding: 24px;
Your design             |  Figma Design
:-------------------------:|:-------------------------:
![dvstudent](https://user-images.githubusercontent.com/69638013/154787855-b5725dce-6bd1-4166-8ade-d463afeee76f.PNG)  | ![dvfigma](https://user-images.githubusercontent.com/69638013/154787858-de3e57e6-06fc-4b51-8c6a-33b30ab29a84.PNG)

- [ ] Kindly fix the content of this div 👍🏿

2022-02-19 05:45 UTC, prolajumokeoni commented on styles.css
> +  }
Your design             |  Figma Design
:-------------------------:|:-------------------------:
![studentlogo](https://user-images.githubusercontent.com/69638013/154787945-47929703-2074-4127-a2c3-5986a7d31eac.PNG)  | ![logomain](https://user-images.githubusercontent.com/69638013/154787953-16351689-de4b-4e78-8b3a-60534a764a22.PNG)

- [ ] Kindly adjust logo to be on one line like the original design 👍🏿

2022-02-19 14:32 UTC, Ibnballo1 commented on index.html
>                  <div class="bgimg">
Thanks, @Donard97 but I actually did not understand this part... It is showing well on my screen, if I should use the figma's width (1440px) it will not cover my screen and in fact, it will look as what you screenshot.

2022-02-19 14:44 UTC, Donard97 commented on index.html
>                  <div class="bgimg">
Hello @Ibnballo1, I hope you are well. When you go with dev tools inspecting your browser where is your project you have a different screen from phone to desktop and when I click on the laptop screen it shows that the design is like the screenshots that I sent.  You can use breakpoint only for the laptop screen and you can fix it. If you have any more questions please can reach me on Slack: Donard Golaj. Keep rocking 💪

2022-02-24 13:16 UTC, closed without merging

2022-02-24 13:17 UTC, Ibnballo1 commented
No more using this file